version: '3.7'
services:
    web:
        build: .
        environment:
            - MONGO_DSN="mongodb://Buba:boba22@mongodb"
        ports:
            - 5000:5000
        depends_on:
            - mongodb

    mongodb:
        image: mongo:5.0
        environment:
            - MONGO_INITDB_ROOT_USERNAME=Buba
            - MONGO_INITDB_ROOT_PASSWORD=boba22
